### Project specific config ###

language: generic

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
    - python3-docutils

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable

    - os: linux
      env: ATOM_CHANNEL=beta

env:
  global:
    APM_TEST_PACKAGES: "language-restructuredtext"

before_script:
  - rst2html --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty
